#!/usr/bin/env python3
"""Tests for changelog-section.py.

This runs unattended on tag push and its output is what every running instance
renders as release notes. A bug here is invisible until someone's dashboard
shows the wrong thing — or the whole changelog.

    python3 scripts/changelog_section_test.py
"""

from __future__ import annotations

import importlib.util
import pathlib
import unittest

_spec = importlib.util.spec_from_file_location(
    "changelog_section", pathlib.Path(__file__).parent / "changelog-section.py"
)
changelog_section = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(changelog_section)

CHANGELOG = """# Changelog

Some preamble that is not part of any release.

## 0.2.0 — 2026-07-27

### Added

- The thing
- The other thing

### Fixed

- A bug

## 0.1.0 — 2026-07-26

### Added

- First release

<!-- generated by git-cliff -->
"""


class Extract(unittest.TestCase):
    def test_it_returns_only_the_requested_version(self):
        section = changelog_section.extract(CHANGELOG, "0.2.0")
        self.assertIn("The thing", section)
        self.assertIn("A bug", section)
        # The bug this catches: a greedy match swallowing every older release,
        # so the dashboard shows the entire history as one release's notes.
        self.assertNotIn("First release", section)

    def test_the_heading_itself_is_not_repeated(self):
        # The dashboard already renders the version as a heading of its own.
        section = changelog_section.extract(CHANGELOG, "0.2.0")
        self.assertNotIn("## 0.2.0", section)

    def test_the_last_section_stops_at_the_generator_comment(self):
        section = changelog_section.extract(CHANGELOG, "0.1.0")
        self.assertIn("First release", section)
        self.assertNotIn("git-cliff", section)

    def test_a_missing_version_returns_empty_rather_than_raising(self):
        # A release with no changelog section should still publish.
        self.assertEqual(changelog_section.extract(CHANGELOG, "9.9.9"), "")

    def test_an_empty_changelog_returns_empty(self):
        self.assertEqual(changelog_section.extract("", "0.1.0"), "")

    def test_a_version_is_not_matched_by_a_longer_one(self):
        # Asking for 0.1.0 must not match a "## 0.1.05" heading.
        text = "## 0.1.05 — 2026-01-01\n\n- Wrong one\n"
        self.assertEqual(changelog_section.extract(text, "0.1.0"), "")

    def test_the_notes_do_not_contain_install_instructions(self):
        # The whole reason this script exists rather than reusing the GitHub
        # release body, which is full of tar and docker run commands.
        section = changelog_section.extract(CHANGELOG, "0.2.0")
        for noise in ["docker run", "tar -xzf", "## Install"]:
            self.assertNotIn(noise, section)


class Cli(unittest.TestCase):
    def test_a_missing_section_falls_back_to_a_pointer(self):
        import io
        import contextlib

        changelog = pathlib.Path("/tmp/nudo-changelog-test.md")
        changelog.write_text(CHANGELOG, encoding="utf-8")

        out = io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(io.StringIO()):
            code = changelog_section.main(["9.9.9", "--changelog", str(changelog)])

        self.assertEqual(code, 0, "a missing section must not fail the release")
        self.assertIn("See the release page", out.getvalue())
        changelog.unlink()

    def test_a_leading_v_is_accepted(self):
        import io
        import contextlib

        changelog = pathlib.Path("/tmp/nudo-changelog-test2.md")
        changelog.write_text(CHANGELOG, encoding="utf-8")

        out = io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(io.StringIO()):
            changelog_section.main(["v0.2.0", "--changelog", str(changelog)])

        self.assertIn("The thing", out.getvalue())
        changelog.unlink()


if __name__ == "__main__":
    unittest.main()
